import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {z} from 'zod';
import * as server from '../lib/server.ts';
process.env.SESSION_SECRET='test-secret-only-not-for-production-'.repeat(2);
process.env.TURSO_DATABASE_URL='libsql://test.turso.io';
process.env.TURSO_AUTH_TOKEN='test-only';
const db=new DatabaseSync(':memory:');
for(const f of ['0000_last_hammerhead.sql','0001_gray_bruce_banner.sql']) db.exec(readFileSync('drizzle/'+f,'utf8'));
const actualFetch=globalThis.fetch;
globalThis.fetch=async(url,options)=>{
 assert.equal(String(url),'https://test.turso.io/v2/pipeline');
 const request=JSON.parse(options.body);assert.equal(request.requests[1].type,'close');
 const {sql,args}=request.requests[0].stmt;
 const values=args.map(a=>a.type==='null'?null:a.type==='integer'?Number(a.value):a.value);
 const stmt=db.prepare(sql);const columns=stmt.columns();let rows=[],affected=0;
 if(columns.length)rows=stmt.all(...values);else affected=Number(stmt.run(...values).changes);
 return Response.json({results:[{type:'ok',response:{result:{cols:columns.map(c=>({name:c.name})),rows:rows.map(r=>columns.map(c=>r[c.name]==null?{type:'null'}:{type:typeof r[c.name]==='number'?'integer':'text',value:String(r[c.name])})),affected_row_count:affected}}},{type:'ok',response:{type:'close'}}]});
};
const token=server.sessionToken('owner');assert.equal(server.identity(new Request('https://example.com',{headers:{cookie:server.sessionCookie(token)}})),'owner');
assert.equal(server.identity(new Request('https://example.com',{headers:{'oai-authenticated-user-id':'forged'}})),null);
assert.equal(server.identity(new Request('https://example.com',{headers:{cookie:server.sessionCookie(token+'tampered')}})),null);
assert.equal(server.validOrigin(new Request('https://example.com',{headers:{origin:'https://attacker.example'}})),false);
const nodeCrypto=await import('node:crypto'), util=await import('node:util');globalThis.authDeps={...server,z,...nodeCrypto,scryptCallback:nodeCrypto.scrypt,...util};
const source=readFileSync('app/api/auth/route.ts','utf8').replace(/^import .*;\r?\n/gm,'');
const auth=await import('data:text/javascript;base64,'+Buffer.from('const {randomBytes,randomUUID,scryptCallback,timingSafeEqual,promisify,z,db,identity,sessionToken,sessionCookie,validOrigin,configured,failure}=globalThis.authDeps;'+ts.transpile(source,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
const request=(mode,password='valid-password-123')=>new Request('https://example.com/api/auth',{method:'POST',headers:{'content-type':'application/json',origin:'https://example.com'},body:JSON.stringify({mode,email:'TEST@example.com',password})});
const signup=await auth.POST(request('register'));assert.equal(signup.status,200);const cookie=signup.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);assert.ok(server.identity(new Request('https://example.com',{headers:{cookie}})));
assert.equal((await auth.POST(request('register'))).status,409);
assert.equal((await auth.POST(request('login','incorrect-password'))).status,401);
assert.equal((await auth.POST(request('login'))).status,200);
const who=await auth.GET(new Request('https://example.com/api/auth',{headers:{cookie}}));assert.equal((await who.json()).user,'test@example.com');
const logout=await auth.DELETE(new Request('https://example.com/api/auth',{method:'DELETE'}));assert.match(logout.headers.get('set-cookie'),/Max-Age=0/);
for(let i=0;i<7;i++)await auth.POST(request('login','incorrect-password'));
assert.equal((await auth.POST(request('login'))).status,429);
globalThis.fetch=async()=>Response.json({results:[{type:'error',error:{message:'failed'}}]});await assert.rejects(server.query('SELECT 1'));
globalThis.fetch=actualFetch;
console.log('Passed: Turso HTTP mapping, signed session, forged headers/cookies, origin validation, registration, login, logout, throttling and database error handling.');
