import { randomBytes, randomUUID, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { z } from 'zod';
import {db,identity,sessionToken,sessionCookie,validOrigin,configured,failure} from '@/lib/server';
const scrypt=promisify(scryptCallback);
const schema=z.object({mode:z.enum(['login','register']),email:z.string().trim().email().max(254).transform(v=>v.toLowerCase()),password:z.string().min(10).max(128)});
export async function GET(r:Request){try{if(!configured())return Response.json({user:null,configured:false},{headers:{'Cache-Control':'no-store'}});const id=identity(r);const user=id?await db().prepare('SELECT email FROM users WHERE id=?').bind(id).first():null;return Response.json({user:user?.email||null,configured:true},{headers:{'Cache-Control':'private, no-store'}})}catch{return failure()}}
export async function POST(r:Request){if(!validOrigin(r))return new Response(null,{status:403});try{const parsed=schema.safeParse(await r.json());if(!parsed.success)return Response.json({error:'Geçerli bir e-posta ve en az 10 karakterli şifre gir.'},{status:400});const {mode,email,password}=parsed.data;const slot=Math.floor(Date.now()/900000);const limiter=await db().prepare('INSERT INTO auth_limits (email,slot,attempts) VALUES (?,?,1) ON CONFLICT(email) DO UPDATE SET slot=excluded.slot,attempts=CASE WHEN auth_limits.slot=excluded.slot THEN auth_limits.attempts+1 ELSE 1 END RETURNING attempts').bind(email,slot).first();if(Number(limiter?.attempts)>10)return Response.json({error:'Çok fazla deneme yaptın. 15 dakika sonra tekrar dene.'},{status:429});let id:string;
if(mode==='register'){const salt=randomBytes(16).toString('hex');const hash=(await scrypt(password,salt,64) as Buffer).toString('hex');id=randomUUID();const result=await db().prepare('INSERT OR IGNORE INTO users (id,email,password_hash) VALUES (?,?,?)').bind(id,email,salt+':'+hash).run();if(!result.meta.changes)return Response.json({error:'Bu e-posta ile kayıt oluşturulamıyor. Mevcut hesabınla giriş yap.'},{status:409})}else{const user=await db().prepare('SELECT id,password_hash FROM users WHERE email=?').bind(email).first();const [salt,stored]=String(user?.password_hash||'00000000000000000000000000000000:'+ '00'.repeat(64)).split(':');const actual=await scrypt(password,salt,64) as Buffer;const expected=Buffer.from(stored,'hex');if(!user||expected.length!==actual.length||!timingSafeEqual(actual,expected))return Response.json({error:'E-posta veya şifre hatalı.'},{status:401});id=String(user.id)}return Response.json({user:email},{headers:{'Set-Cookie':sessionCookie(sessionToken(id)),'Cache-Control':'no-store'}})}catch(e){console.error('Authentication failed');return failure()}}
export async function DELETE(r:Request){if(!validOrigin(r))return new Response(null,{status:403});return Response.json({ok:true},{headers:{'Set-Cookie':sessionCookie('',0),'Cache-Control':'no-store'}})}
