'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function Account(){
 const [user,setUser]=useState<string|null>(null),[open,setOpen]=useState(false),[register,setRegister]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[setup,setSetup]=useState(false),[checking,setChecking]=useState(true);
 async function refresh(){setChecking(true);try{const r=await fetch('/api/auth',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Hesap bilgisi yüklenemedi.');setUser(d.user);setSetup(d.configured===false);setError('')}catch(err){setError((err as Error).message)}finally{setChecking(false)}}
 useEffect(()=>{void refresh();const show=()=>{setOpen(true);void refresh()};window.addEventListener('isbul:sign-in',show);return()=>window.removeEventListener('isbul:sign-in',show)},[]);
 return <><div className="account"><button onClick={()=>{setOpen(true);void refresh()}}>{user?'Hesabım':'Giriş / Kayıt'}</button></div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogTitle>{user?'Hesabım':register?'Hesap oluştur':'Giriş yap'}</DialogTitle><DialogDescription>{user||'İlanlarını ve başvurularını hesabınla takip et.'}</DialogDescription>
 {checking?<p>Hesap kontrol ediliyor…</p>:setup?<p role="alert">Site yöneticisinin veritabanı ve oturum ayarlarını tamamlaması gerekiyor.</p>:user?<button className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/auth',{method:'DELETE'});if(!r.ok)throw Error();location.reload()}catch{setError('Çıkış yapılamadı. Tekrar dene.');setBusy(false)}}}>Çıkış yap</button>:<form className="form-dialog" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(new FormData(e.currentTarget)),mode:register?'register':'login'})});const d=await r.json();if(!r.ok)throw Error(d.error||'İşlem tamamlanamadı.');setUser(d.user);setOpen(false);window.dispatchEvent(new Event('isbul:authenticated'))}catch(err){setError((err as Error).message)}finally{setBusy(false)}}}>
 <label>E-posta<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><label>Şifre<input name="password" type="password" autoComplete={register?'new-password':'current-password'} required minLength={10} maxLength={128} placeholder="En az 10 karakter"/></label><button className="primary full" disabled={busy}>{busy?'Bekleyin…':register?'Kayıt ol':'Giriş yap'}</button><button type="button" className="reset" onClick={()=>{setRegister(!register);setError('')}}>{register?'Hesabın var mı? Giriş yap':'Hesabın yok mu? Kayıt ol'}</button></form>}
 {error&&<p role="alert" className="notice">{error}</p>}</DialogContent></Dialog></>;
}
