import { createHmac, timingSafeEqual } from 'node:crypto';
export function configured(){return !!(process.env.TURSO_DATABASE_URL&&process.env.TURSO_AUTH_TOKEN&&process.env.SESSION_SECRET&&process.env.SESSION_SECRET.length>=32)}
function secret(){const value=process.env.SESSION_SECRET;if(!value||value.length<32)throw Error('SESSION_SECRET must have at least 32 characters');return value}
export function sessionToken(id:string){const payload=Buffer.from(JSON.stringify({id,exp:Date.now()+7*86400000})).toString('base64url');return payload+'.'+createHmac('sha256',secret()).update(payload).digest('base64url')}
export function identity(r:Request){const token=r.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith('isbul_session='))?.slice(14);if(!token)return null;try{const [payload,signature,...extra]=token.split('.');if(extra.length||!payload||!signature)return null;const expected=createHmac('sha256',secret()).update(payload).digest();const supplied=Buffer.from(signature,'base64url');if(supplied.length!==expected.length||!timingSafeEqual(supplied,expected))return null;const data=JSON.parse(Buffer.from(payload,'base64url').toString());return typeof data.id==='string'&&data.exp>Date.now()?data.id:null}catch{return null}}
export function sessionCookie(token:string,maxAge=604800){return `isbul_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${maxAge}${process.env.NODE_ENV==='production'?'; Secure':''}`}
export async function query(sql:string,args:unknown[]=[]){const raw=process.env.TURSO_DATABASE_URL,token=process.env.TURSO_AUTH_TOKEN;if(!raw||!token)throw Error('Database is not configured');const url=new URL(raw.replace(/^(libsql|turso):/, 'https:'));if(url.protocol!=='https:')throw Error('Database must use HTTPS');const response=await fetch(new URL('/v2/pipeline',url),{method:'POST',cache:'no-store',signal:AbortSignal.timeout(15000),headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({requests:[{type:'execute',stmt:{sql,args:args.map(value=>value==null?{type:'null'}:typeof value==='number'?{type:Number.isInteger(value)?'integer':'float',value:Number.isInteger(value)?String(value):value}:{type:'text',value:String(value)})}},{type:'close'}]})});if(!response.ok)throw Error('Database request failed');const body=await response.json();const entry=body.results?.[0];if(entry?.type!=='ok')throw Error('Database query failed');const result=entry.response.result;return {results:result.rows.map((row:{type:string;value?:string|number}[])=>Object.fromEntries(result.cols.map((col:{name:string},i:number)=>[col.name,row[i].type==='null'?null:['integer','float'].includes(row[i].type)?Number(row[i].value):row[i].value]))) as Record<string,unknown>[],meta:{changes:result.affected_row_count}}}
export function db(){return {prepare(sql:string){return {bind(...args:unknown[]){return {all:()=>query(sql,args),run:()=>query(sql,args),first:async()=>{const r=await query(sql,args);return r.results[0]||null}}}}}}}
export function failure(){return Response.json({error:configured()?'İşlem tamamlanamadı. Lütfen tekrar deneyin.':'Site kurulumu tamamlanmamış. Veritabanı ve oturum ayarları gerekli.'},{status:503})}
export function unauthorized(){return Response.json({error:'İşleme devam etmek için giriş yapmalısın.'},{status:401})}
export function validOrigin(r:Request){const origin=r.headers.get('origin');return !origin||origin===new URL(r.url).origin}
